package prestamo;

import Alertas.ErrorRegistro;
import Alertas.Registro;
import Alertas.RellenarCampos;
import com.sun.awt.AWTUtilities;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Raomir
 */
public class Nuevo extends javax.swing.JFrame {

    /**
     * Creates new form Nuevo
     */
    public Nuevo() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        rSPanelsSlider1 = new rojeru_san.RSPanelsSlider();
        jLabel1 = new javax.swing.JLabel();
        txtApellidos = new rojeru_san.RSMTextFull();
        txtNombres = new rojeru_san.RSMTextFull();
        txtDocumento = new rojeru_san.RSMTextFull();
        txtLibro = new rojeru_san.RSMTextFull();
        txtAutor = new rojeru_san.RSMTextFull();
        txtPasillo = new rojeru_san.RSMTextFull();
        txtCategoria = new rojeru_san.RSMTextFull();
        txtSeccion = new rojeru_san.RSMTextFull();
        txtTema = new rojeru_san.RSMTextFull();
        btnCancelar = new rojeru_san.RSButton();
        btnRegistrar = new rojeru_san.RSButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        rSPanelsSlider1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nuevo prestamo");
        rSPanelsSlider1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 170, 68));

        txtApellidos.setEditable(false);
        txtApellidos.setBackground(new java.awt.Color(255, 255, 255));
        txtApellidos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtApellidos.setBordeColorFocus(new java.awt.Color(204, 204, 204));
        txtApellidos.setBotonColor(new java.awt.Color(255, 255, 255));
        txtApellidos.setFont(new java.awt.Font("Roboto Bold", 0, 14)); // NOI18N
        txtApellidos.setMayusculas(true);
        txtApellidos.setPlaceholder("Apellidos...");

        txtNombres.setEditable(false);
        txtNombres.setBackground(new java.awt.Color(255, 255, 255));
        txtNombres.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombres.setBordeColorFocus(new java.awt.Color(204, 204, 204));
        txtNombres.setBotonColor(new java.awt.Color(255, 255, 255));
        txtNombres.setFont(new java.awt.Font("Roboto Bold", 0, 14)); // NOI18N
        txtNombres.setMayusculas(true);
        txtNombres.setPlaceholder("Nombres...");

        txtDocumento.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDocumento.setBordeColorFocus(new java.awt.Color(204, 204, 204));
        txtDocumento.setPlaceholder("Núimero de identificación");
        txtDocumento.setSoloNumeros(true);
        txtDocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDocumentoKeyReleased(evt);
            }
        });

        txtLibro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtLibro.setBordeColorFocus(new java.awt.Color(204, 204, 204));
        txtLibro.setMayusculas(true);
        txtLibro.setPlaceholder("Nombre del libro...");
        txtLibro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLibroKeyReleased(evt);
            }
        });

        txtAutor.setEditable(false);
        txtAutor.setBackground(new java.awt.Color(255, 255, 255));
        txtAutor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAutor.setBordeColorFocus(new java.awt.Color(204, 204, 204));
        txtAutor.setBotonColor(new java.awt.Color(255, 255, 255));
        txtAutor.setFont(new java.awt.Font("Roboto Bold", 0, 14)); // NOI18N
        txtAutor.setMayusculas(true);
        txtAutor.setPlaceholder("Autor");

        txtPasillo.setEditable(false);
        txtPasillo.setBackground(new java.awt.Color(255, 255, 255));
        txtPasillo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPasillo.setBordeColorFocus(new java.awt.Color(204, 204, 204));
        txtPasillo.setBotonColor(new java.awt.Color(255, 255, 255));
        txtPasillo.setFont(new java.awt.Font("Roboto Bold", 0, 14)); // NOI18N
        txtPasillo.setMayusculas(true);
        txtPasillo.setPlaceholder("Pasillo");

        txtCategoria.setEditable(false);
        txtCategoria.setBackground(new java.awt.Color(255, 255, 255));
        txtCategoria.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCategoria.setBordeColorFocus(new java.awt.Color(204, 204, 204));
        txtCategoria.setBotonColor(new java.awt.Color(255, 255, 255));
        txtCategoria.setFont(new java.awt.Font("Roboto Bold", 0, 14)); // NOI18N
        txtCategoria.setMayusculas(true);
        txtCategoria.setPlaceholder("Categoría...");

        txtSeccion.setEditable(false);
        txtSeccion.setBackground(new java.awt.Color(255, 255, 255));
        txtSeccion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSeccion.setBordeColorFocus(new java.awt.Color(204, 204, 204));
        txtSeccion.setBotonColor(new java.awt.Color(255, 255, 255));
        txtSeccion.setFont(new java.awt.Font("Roboto Bold", 0, 14)); // NOI18N
        txtSeccion.setMayusculas(true);
        txtSeccion.setPlaceholder("Sección...");
        txtSeccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSeccionActionPerformed(evt);
            }
        });

        txtTema.setEditable(false);
        txtTema.setBackground(new java.awt.Color(255, 255, 255));
        txtTema.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTema.setBordeColorFocus(new java.awt.Color(204, 204, 204));
        txtTema.setBotonColor(new java.awt.Color(255, 255, 255));
        txtTema.setFont(new java.awt.Font("Roboto Bold", 0, 14)); // NOI18N
        txtTema.setMayusculas(true);
        txtTema.setPlaceholder("Tema...");

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelsSlider1, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(103, 103, 103)
                                        .addComponent(txtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtTema, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtPasillo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtSeccion, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(txtLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(rSPanelsSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(txtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSeccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(txtLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPasillo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAutor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDocumentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDocumentoKeyReleased
        int code = evt.getKeyCode();
        if (code == 10) {
            Opciones op = new Opciones();
            op.ingresarEstudiante(txtDocumento.getText());
        }
        Sentencias s = new Sentencias();
        s.setDocumento(txtDocumento.getText());
    }//GEN-LAST:event_txtDocumentoKeyReleased

    private void txtLibroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLibroKeyReleased
        int code = evt.getKeyCode();
        if (code == 10) {
            Opciones op = new Opciones();
            op.ingresarLibro(txtLibro.getText());
        }
        Sentencias s = new Sentencias();
        s.setLibro(txtLibro.getText());
    }//GEN-LAST:event_txtLibroKeyReleased

    private void txtSeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSeccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSeccionActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        getCamposVacios();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed
    
    private void getCamposVacios(){
        if (txtApellidos.getText().isEmpty() && txtNombres.getText().isEmpty()  && txtSeccion.getText().isEmpty()) {
            if (txtAutor.getText().isEmpty() && txtCategoria.getText().isEmpty() && txtPasillo.getText().isEmpty() && txtTema.getText().isEmpty()) {
                RellenarCampos re = new RellenarCampos();
                re.setVisible(true);
            }else{
                RellenarCampos re = new RellenarCampos();
                re.setVisible(true);
            }
        } else {
            if (txtAutor.getText().isEmpty() && txtCategoria.getText().isEmpty() && txtPasillo.getText().isEmpty() && txtTema.getText().isEmpty()) {
                RellenarCampos re = new RellenarCampos();
                re.setVisible(true);
            }else{
                Opciones op = new Opciones();
                int a = op.actualizarCantidadLibro();
                op.listarPersonal("");
                getLimpiarCampos();
                if (a == 1) {
                    Registro re = new Registro();
                    re.lblNombre.setText("prestamo");
                    re.setVisible(true);
                }else{
                    ErrorRegistro er = new ErrorRegistro();
                    er.setVisible(true);
                }
            }
        }
    }
    
    private void getLimpiarCampos(){
        txtApellidos.setText("");
        txtAutor.setText("");
        txtCategoria.setText("");
        txtDocumento.setText("");
        txtLibro.setText("");
        txtNombres.setText("");
        txtPasillo.setText("");
        txtSeccion.setText("");
        txtTema.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nuevo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButton btnCancelar;
    private rojeru_san.RSButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private rojeru_san.RSPanelsSlider rSPanelsSlider1;
    protected static rojeru_san.RSMTextFull txtApellidos;
    protected static rojeru_san.RSMTextFull txtAutor;
    protected static rojeru_san.RSMTextFull txtCategoria;
    protected static rojeru_san.RSMTextFull txtDocumento;
    protected static rojeru_san.RSMTextFull txtLibro;
    protected static rojeru_san.RSMTextFull txtNombres;
    protected static rojeru_san.RSMTextFull txtPasillo;
    protected static rojeru_san.RSMTextFull txtSeccion;
    protected static rojeru_san.RSMTextFull txtTema;
    // End of variables declaration//GEN-END:variables
}
