package estudiante;

import Alertas.ErrorRegistro;
import Alertas.Registro;
import Alertas.RellenarCampos;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Raomir
 */
public class Nuevo extends javax.swing.JFrame {

    /**
     * Creates new form Nuevo
     */
    Sentencias s = new Sentencias();
    public Nuevo() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDocumento2 = new rojeru_san.RSMTextFull();
        jPanel1 = new javax.swing.JPanel();
        rSPanelsSlider1 = new rojeru_san.RSPanelsSlider();
        jLabel1 = new javax.swing.JLabel();
        txtApellidos = new rojeru_san.RSMTextFull();
        txtNombres = new rojeru_san.RSMTextFull();
        txtSeccion = new rojeru_san.RSMTextFull();
        btnCancelar = new rojeru_san.RSButton();
        btnRegistrar = new rojeru_san.RSButton();
        txtTelefono = new rojeru_san.RSMTextFull();
        txtDireccion = new rojeru_san.RSMTextFull();
        txtDocumento = new rojeru_san.RSMTextFull();

        txtDocumento2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDocumento2.setBordeColorFocus(new java.awt.Color(204, 204, 204));
        txtDocumento2.setPlaceholder("Núimero de identificación");
        txtDocumento2.setSoloNumeros(true);
        txtDocumento2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDocumento2KeyReleased(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSPanelsSlider1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registrar Estudiante");
        rSPanelsSlider1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 210, 68));

        jPanel1.add(rSPanelsSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 520, -1));

        txtApellidos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtApellidos.setBordeColorFocus(new java.awt.Color(204, 204, 204));
        txtApellidos.setMayusculas(true);
        txtApellidos.setPlaceholder("Apellidos...");
        txtApellidos.setSoloLetras(true);
        jPanel1.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 193, -1));

        txtNombres.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombres.setBordeColorFocus(new java.awt.Color(204, 204, 204));
        txtNombres.setMayusculas(true);
        txtNombres.setPlaceholder("Nombres...");
        txtNombres.setSoloLetras(true);
        jPanel1.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 190, -1));

        txtSeccion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSeccion.setBordeColorFocus(new java.awt.Color(204, 204, 204));
        txtSeccion.setPlaceholder("Sección...");
        txtSeccion.setSoloNumeros(true);
        txtSeccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSeccionKeyReleased(evt);
            }
        });
        jPanel1.add(txtSeccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 193, -1));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 127, -1));

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 127, -1));

        txtTelefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTelefono.setBordeColorFocus(new java.awt.Color(204, 204, 204));
        txtTelefono.setPlaceholder("Telefono...");
        txtTelefono.setSoloNumeros(true);
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyReleased(evt);
            }
        });
        jPanel1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 193, -1));

        txtDireccion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDireccion.setBordeColorFocus(new java.awt.Color(204, 204, 204));
        txtDireccion.setPlaceholder("Dirección...");
        txtDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDireccionKeyReleased(evt);
            }
        });
        jPanel1.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 193, -1));

        txtDocumento.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDocumento.setBordeColorFocus(new java.awt.Color(204, 204, 204));
        txtDocumento.setPlaceholder("Número de identificación");
        txtDocumento.setSoloNumeros(true);
        txtDocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDocumentoKeyReleased(evt);
            }
        });
        jPanel1.add(txtDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 193, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSeccionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSeccionKeyReleased
     
    }//GEN-LAST:event_txtSeccionKeyReleased

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        s.setNombres(txtNombres.getText());
        s.setApellidos(txtApellidos.getText());
        s.setDocumento(txtDocumento.getText());
        s.setDireccion(txtDireccion.getText());
        s.setTelefono(txtTelefono.getText());
        s.setSeccion(txtSeccion.getText());
        getCamposVacios();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtTelefonoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoKeyReleased

    private void txtDocumento2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDocumento2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDocumento2KeyReleased

    private void txtDireccionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDireccionKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionKeyReleased

    private void txtDocumentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDocumentoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDocumentoKeyReleased
    
    private void getCamposVacios(){
        if ((!txtNombres.getText().isEmpty() && !txtApellidos.getText().isEmpty()) && (!txtDocumento.getText().isEmpty() && !txtDireccion.getText().isEmpty())
                && (!txtTelefono.getText().isEmpty() && !txtSeccion.getText().isEmpty())) {
            
            Opciones op = new Opciones();
            int rsu = op.ingresarEstudiante();
            
            if (rsu == 1) {
                    Registro re = new Registro();
                    re.lblNombre.setText("estudiante");
                    re.setVisible(true);
                    op.listarEstudiante("");
                    getLimpiarCampos();
            }else{
                    ErrorRegistro er = new ErrorRegistro();
                    er.setVisible(true);
                }       
        } else {
            RellenarCampos re = new RellenarCampos();
            re.setVisible(true);    
        }
    }
    
    private void getLimpiarCampos(){
        txtNombres.setText("");
        txtApellidos.setText("");
        txtDocumento.setText("");
        txtDireccion.setText("");
        txtTelefono.setText("");
        txtSeccion.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nuevo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButton btnCancelar;
    private rojeru_san.RSButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private rojeru_san.RSPanelsSlider rSPanelsSlider1;
    protected static rojeru_san.RSMTextFull txtApellidos;
    protected static rojeru_san.RSMTextFull txtDireccion;
    protected static rojeru_san.RSMTextFull txtDocumento;
    protected static rojeru_san.RSMTextFull txtDocumento2;
    protected static rojeru_san.RSMTextFull txtNombres;
    protected static rojeru_san.RSMTextFull txtSeccion;
    protected static rojeru_san.RSMTextFull txtTelefono;
    // End of variables declaration//GEN-END:variables
}
