/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menu;

import libro.Actualizar;
import sesion.Login;

/**
 *
 * @author Raomir
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */    
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        rSPanelsSlider1 = new rojeru_san.RSPanelsSlider();
        jLabel1 = new javax.swing.JLabel();
        rSButton1 = new rojeru_san.RSButton();
        rSButton2 = new rojeru_san.RSButton();
        jPanel2 = new javax.swing.JPanel();
        btnPrestamo = new rojeru_san.RSButtonRiple();
        btnEstudiante = new rojeru_san.RSButtonRiple();
        rSButtonRiple3 = new rojeru_san.RSButtonRiple();
        rSButtonRiple6 = new rojeru_san.RSButtonRiple();
        rSButtonRiple5 = new rojeru_san.RSButtonRiple();
        rSButtonRiple7 = new rojeru_san.RSButtonRiple();
        rSButtonRiple8 = new rojeru_san.RSButtonRiple();
        rSButtonRiple9 = new rojeru_san.RSButtonRiple();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSPanelsSlider1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 2, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BIBLIOINEM");
        rSPanelsSlider1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 400, -1));

        rSButton1.setBackground(new java.awt.Color(255, 255, 255));
        rSButton1.setText("X");
        rSButton1.setColorText(new java.awt.Color(0, 112, 192));
        rSButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButton1ActionPerformed(evt);
            }
        });
        rSPanelsSlider1.add(rSButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 10, 50, -1));

        rSButton2.setBackground(new java.awt.Color(255, 255, 255));
        rSButton2.setForeground(new java.awt.Color(0, 112, 192));
        rSButton2.setText("-");
        rSButton2.setColorText(new java.awt.Color(0, 112, 192));
        rSButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButton2ActionPerformed(evt);
            }
        });
        rSPanelsSlider1.add(rSButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 10, 50, 40));

        jPanel1.add(rSPanelsSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1410, 102));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));

        btnPrestamo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 112, 192), 2, true));
        btnPrestamo.setText("Prestamo");
        btnPrestamo.setColorHover(new java.awt.Color(255, 255, 255));
        btnPrestamo.setColorTextHover(new java.awt.Color(0, 112, 192));
        btnPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrestamoActionPerformed(evt);
            }
        });

        btnEstudiante.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 112, 192), 2, true));
        btnEstudiante.setText("Estudiantes");
        btnEstudiante.setColorHover(new java.awt.Color(255, 255, 255));
        btnEstudiante.setColorTextHover(new java.awt.Color(0, 112, 192));
        btnEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstudianteActionPerformed(evt);
            }
        });

        rSButtonRiple3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 112, 192), 2, true));
        rSButtonRiple3.setText("Libros");
        rSButtonRiple3.setColorHover(new java.awt.Color(255, 255, 255));
        rSButtonRiple3.setColorTextHover(new java.awt.Color(0, 112, 192));
        rSButtonRiple3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRiple3ActionPerformed(evt);
            }
        });

        rSButtonRiple6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 112, 192), 2, true));
        rSButtonRiple6.setText("Cerrar Sesión");
        rSButtonRiple6.setColorHover(new java.awt.Color(255, 255, 255));
        rSButtonRiple6.setColorTextHover(new java.awt.Color(0, 112, 192));
        rSButtonRiple6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRiple6ActionPerformed(evt);
            }
        });

        rSButtonRiple5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 112, 192), 2, true));
        rSButtonRiple5.setText("Autores");
        rSButtonRiple5.setColorHover(new java.awt.Color(255, 255, 255));
        rSButtonRiple5.setColorTextHover(new java.awt.Color(0, 112, 192));
        rSButtonRiple5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRiple5ActionPerformed(evt);
            }
        });

        rSButtonRiple7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 112, 192), 2, true));
        rSButtonRiple7.setText("Temas");
        rSButtonRiple7.setColorHover(new java.awt.Color(255, 255, 255));
        rSButtonRiple7.setColorTextHover(new java.awt.Color(0, 112, 192));
        rSButtonRiple7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRiple7ActionPerformed(evt);
            }
        });

        rSButtonRiple8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 112, 192), 2, true));
        rSButtonRiple8.setText("Categorías");
        rSButtonRiple8.setColorHover(new java.awt.Color(255, 255, 255));
        rSButtonRiple8.setColorTextHover(new java.awt.Color(0, 112, 192));
        rSButtonRiple8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRiple8ActionPerformed(evt);
            }
        });

        rSButtonRiple9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 112, 192), 2, true));
        rSButtonRiple9.setText("Ejemplares");
        rSButtonRiple9.setColorHover(new java.awt.Color(255, 255, 255));
        rSButtonRiple9.setColorTextHover(new java.awt.Color(0, 112, 192));
        rSButtonRiple9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRiple9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rSButtonRiple9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSButtonRiple8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSButtonRiple7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSButtonRiple5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSButtonRiple6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSButtonRiple3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(btnPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rSButtonRiple3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rSButtonRiple5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rSButtonRiple7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rSButtonRiple8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rSButtonRiple9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(rSButtonRiple6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, 550));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setMinimumSize(new java.awt.Dimension(630, 444));
        jPanel4.setPreferredSize(new java.awt.Dimension(630, 444));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));
        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 1070, 550));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrestamoActionPerformed
        new CambiaPanel.CambiaPanel(jPanel4, new prestamo.Lista());
    }//GEN-LAST:event_btnPrestamoActionPerformed

    private void btnEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstudianteActionPerformed
        new CambiaPanel.CambiaPanel(jPanel4, new estudiante.Lista());
    }//GEN-LAST:event_btnEstudianteActionPerformed

    private void rSButtonRiple3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRiple3ActionPerformed
        new CambiaPanel.CambiaPanel(jPanel4, new libro.Lista());
    }//GEN-LAST:event_rSButtonRiple3ActionPerformed

    private void rSButtonRiple6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRiple6ActionPerformed
        Login obj = new Login();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_rSButtonRiple6ActionPerformed

    private void rSButtonRiple5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRiple5ActionPerformed
        new CambiaPanel.CambiaPanel(jPanel4, new autor.Lista());
    }//GEN-LAST:event_rSButtonRiple5ActionPerformed

    private void rSButtonRiple7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRiple7ActionPerformed
        new CambiaPanel.CambiaPanel(jPanel4, new tema.Lista());
    }//GEN-LAST:event_rSButtonRiple7ActionPerformed

    private void rSButtonRiple8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRiple8ActionPerformed
        new CambiaPanel.CambiaPanel(jPanel4, new categoria.Lista());
    }//GEN-LAST:event_rSButtonRiple8ActionPerformed

    private void rSButtonRiple9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRiple9ActionPerformed
        new CambiaPanel.CambiaPanel(jPanel4, new ejemplares.Lista());
    }//GEN-LAST:event_rSButtonRiple9ActionPerformed

    private void rSButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButton1ActionPerformed
      System.exit(0);
    }//GEN-LAST:event_rSButton1ActionPerformed

    private void rSButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButton2ActionPerformed
          setExtendedState(1);
    }//GEN-LAST:event_rSButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Principal obj = new Principal();
                //obj.setExtendedState(MAXIMIZED_BOTH);
                obj.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButtonRiple btnEstudiante;
    private rojeru_san.RSButtonRiple btnPrestamo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JPanel jPanel4;
    private rojeru_san.RSButton rSButton1;
    private rojeru_san.RSButton rSButton2;
    private rojeru_san.RSButtonRiple rSButtonRiple3;
    private rojeru_san.RSButtonRiple rSButtonRiple5;
    private rojeru_san.RSButtonRiple rSButtonRiple6;
    private rojeru_san.RSButtonRiple rSButtonRiple7;
    private rojeru_san.RSButtonRiple rSButtonRiple8;
    private rojeru_san.RSButtonRiple rSButtonRiple9;
    private rojeru_san.RSPanelsSlider rSPanelsSlider1;
    // End of variables declaration//GEN-END:variables
}
