package libro;

import Alertas.ErrorRegistro;
import Alertas.Registro;
import Alertas.RellenarCampos;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Raomir
 */
public class Nuevo extends javax.swing.JFrame {

    /**
     * Creates new form Nuevo
     */
    Sentencias s = new Sentencias();
    Opciones op = new Opciones();
    public Nuevo() {
        initComponents();
        this.setLocationRelativeTo(this);
        
        op.llenarAutor(cmbAutor);
        op.llenarEdicion(cmbEdicion);
        op.llenarPasillo(cmbPasillo);
        op.llenarCategoria(cmbCategoria);
        op.llenarTema(cmbTema);
        
        txtCantidad.setText("0");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDocumento2 = new rojeru_san.RSMTextFull();
        jPanel1 = new javax.swing.JPanel();
        rSPanelsSlider1 = new rojeru_san.RSPanelsSlider();
        jLabel1 = new javax.swing.JLabel();
        txtTitulo = new rojeru_san.RSMTextFull();
        btnCancelar = new rojeru_san.RSButton();
        btnRegistrar = new rojeru_san.RSButton();
        cmbPasillo = new org.edisoncor.gui.comboBox.ComboBoxRound();
        cmbAutor = new org.edisoncor.gui.comboBox.ComboBoxRound();
        cmbCategoria = new org.edisoncor.gui.comboBox.ComboBoxRound();
        cmbEdicion = new org.edisoncor.gui.comboBox.ComboBoxRound();
        txtEditorial = new rojeru_san.RSMTextFull();
        txtIdioma = new rojeru_san.RSMTextFull();
        cmbTema = new org.edisoncor.gui.comboBox.ComboBoxRound();
        txtCantidad = new rojeru_san.RSMTextFull();

        txtDocumento2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDocumento2.setBordeColorFocus(new java.awt.Color(204, 204, 204));
        txtDocumento2.setPlaceholder("Núimero de identificación");
        txtDocumento2.setSoloNumeros(true);
        txtDocumento2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDocumento2KeyReleased(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSPanelsSlider1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registrar Libro");
        rSPanelsSlider1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 210, 68));

        jPanel1.add(rSPanelsSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 520, -1));

        txtTitulo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTitulo.setBordeColorFocus(new java.awt.Color(204, 204, 204));
        txtTitulo.setMayusculas(true);
        txtTitulo.setPlaceholder("Titulo...");
        txtTitulo.setSoloLetras(true);
        jPanel1.add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 190, -1));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, 127, -1));

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, 127, -1));

        cmbPasillo.setForeground(new java.awt.Color(0, 112, 192));
        cmbPasillo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<<Pasillo>>" }));
        cmbPasillo.setColorDeBorde(new java.awt.Color(0, 112, 192));
        jPanel1.add(cmbPasillo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 160, 20));

        cmbAutor.setForeground(new java.awt.Color(0, 112, 192));
        cmbAutor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<<Autor>>" }));
        cmbAutor.setColorDeBorde(new java.awt.Color(0, 112, 192));
        jPanel1.add(cmbAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 160, -1));

        cmbCategoria.setForeground(new java.awt.Color(0, 112, 192));
        cmbCategoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<<Categoría>>" }));
        cmbCategoria.setColorDeBorde(new java.awt.Color(0, 112, 192));
        jPanel1.add(cmbCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 160, 20));

        cmbEdicion.setForeground(new java.awt.Color(0, 112, 192));
        cmbEdicion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<<Edición>>" }));
        cmbEdicion.setColorDeBorde(new java.awt.Color(0, 112, 192));
        jPanel1.add(cmbEdicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 160, 20));

        txtEditorial.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEditorial.setBordeColorFocus(new java.awt.Color(204, 204, 204));
        txtEditorial.setPlaceholder("Editorial...");
        txtEditorial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEditorialKeyReleased(evt);
            }
        });
        jPanel1.add(txtEditorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 193, -1));

        txtIdioma.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtIdioma.setBordeColorFocus(new java.awt.Color(204, 204, 204));
        txtIdioma.setPlaceholder("Idioma...");
        txtIdioma.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIdiomaKeyReleased(evt);
            }
        });
        jPanel1.add(txtIdioma, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 193, -1));

        cmbTema.setForeground(new java.awt.Color(0, 112, 192));
        cmbTema.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<<Tema>>" }));
        cmbTema.setColorDeBorde(new java.awt.Color(0, 112, 192));
        jPanel1.add(cmbTema, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 160, 20));

        txtCantidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantidad.setBordeColorFocus(new java.awt.Color(204, 204, 204));
        txtCantidad.setPlaceholder("Cantidad...");
        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCantidadKeyReleased(evt);
            }
        });
        jPanel1.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 193, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDocumento2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDocumento2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDocumento2KeyReleased

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        s.setTitulo(txtTitulo.getText());
        s.setNombreAutor(cmbAutor.getSelectedItem().toString());
        s.setCategoría(cmbCategoria.getSelectedItem().toString());
        s.setEdicion(cmbEdicion.getSelectedItem().toString());
        s.setEditorial(txtEditorial.getText());
        s.setIdioma(txtIdioma.getText());
        s.setNombreTema(cmbTema.getSelectedItem().toString());
        s.setPasillo(cmbPasillo.getSelectedItem().toString());
        s.setCantidad(Double.parseDouble(txtCantidad.getText()));
        getCamposVacios();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void txtEditorialKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEditorialKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEditorialKeyReleased

    private void txtIdiomaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdiomaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdiomaKeyReleased

    private void txtCantidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadKeyReleased
    
    private void getCamposVacios(){
        if ((!txtTitulo.getText().isEmpty() && cmbTema.getSelectedIndex() != 0) && 
                (!txtEditorial.getText().isEmpty() && !txtIdioma.getText().isEmpty())
                && (cmbAutor.getSelectedIndex() != 0 && cmbEdicion.getSelectedIndex() != 0 ) &&
                (cmbPasillo.getSelectedIndex() !=0 && cmbCategoria.getSelectedIndex() !=0)) {
            
            int rsu = op.ingresarLibro();
            if (rsu == 1) {
                    Registro re = new Registro();
                    re.lblNombre.setText("libro");
                    re.setVisible(true);
                    op.listarLibro("");
                    getLimpiarCampos();
            }else{
                    ErrorRegistro er = new ErrorRegistro();
                    er.setVisible(true);
                }       
        } else {
            RellenarCampos re = new RellenarCampos();
            re.setVisible(true);    
        }
    }
    
    private void getLimpiarCampos(){
        txtTitulo.setText("");
        txtEditorial.setText("");
        txtIdioma.setText("");
        txtCantidad.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nuevo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButton btnCancelar;
    private rojeru_san.RSButton btnRegistrar;
    public static org.edisoncor.gui.comboBox.ComboBoxRound cmbAutor;
    protected static org.edisoncor.gui.comboBox.ComboBoxRound cmbCategoria;
    protected static org.edisoncor.gui.comboBox.ComboBoxRound cmbEdicion;
    protected static org.edisoncor.gui.comboBox.ComboBoxRound cmbPasillo;
    protected static org.edisoncor.gui.comboBox.ComboBoxRound cmbTema;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private rojeru_san.RSPanelsSlider rSPanelsSlider1;
    protected static rojeru_san.RSMTextFull txtCantidad;
    protected static rojeru_san.RSMTextFull txtDocumento2;
    protected static rojeru_san.RSMTextFull txtEditorial;
    protected static rojeru_san.RSMTextFull txtIdioma;
    protected static rojeru_san.RSMTextFull txtTitulo;
    // End of variables declaration//GEN-END:variables
}
